name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: mihails-strasuns/setup-dlang@v0.3.0
      with:
        compiler: dmd-2.090.0
    - name: Run tests
      run: dub test
